name: Get version

outputs:
  version:
    value: ${{ steps.get-version.outputs.version }}
    
runs:
  using: 'composite'
  steps:
    - name: Get version
      uses: actions/checkout@v3
      id: get-version
      run: |
        version=$(git describe --abbrev=0 --tags)
        echo "::set-output name=version::${version##v}"
