name: Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      project-path:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET version
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: |
          dotnet restore ${{ inputs.project-path }}

      - name: Build project
        run: |
          dotnet build ${{ inputs.project-path }} \
          --configuration Release
