name: Get version

on:
  workflow_call:
    outputs:
      version: ${{ steps.get-version.outputs.version }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get version
        uses: actions/checkout@v3
        id: get-version
        run: |
          version=$(git describe --abbrev=0 --tags)
          echo "::set-output name=version::${version##v}"