name: Publish

on:
  workflow_call:
    inputs:
      project-path:
        type: string
      nuget-url:
        required: true
        type: string
    secrets:
      nuget-api-key:
        required: true

env:
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}/output

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Get package version
        id: get-version
        uses: ./.github/actions/get-version.yml@main

      - name: Pack project
        run: |
          dotnet pack ${{ inputs.project-path }} \
          --no-restore \
          --no-build \
          --configuration Release \
          --include-symbols \
          --output ${{ env.PACKAGE_OUTPUT_PATH }}
          -p:PackageVersion=${{ steps.get-version.outputs.version }} \

      - name: Publish to NuGet gallery
        run: |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.nupkg \
          -s ${{ inputs.nuget-url }}
          -k ${{ secrets.nuget-api-key }} \
          /p:PackageVersion=${{ steps.get-version.outputs.version }}
