name: Publish

on:
  workflow_call:
    inputs:
      project-path:
        type: string
      nuget-url:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
    secrets:
      nuget-api-key:
        required: true

env:
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}/output

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET version
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: |
          dotnet restore ${{ inputs.project-path }}

      - name: Build project
        run: |
          dotnet build ${{ inputs.project-path }} \
          --configuration Release

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack project
        run: |
          dotnet pack ${{ inputs.project-path }} \
          --no-restore \
          --no-build \
          --configuration Release \
          --include-symbols \
          --output ${{ env.PACKAGE_OUTPUT_PATH }} \
          -p:PackageVersion=${{ steps.version.outputs.version-without-v }}

      - name: Publish to NuGet gallery
        run: |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.nupkg \
          --source ${{ inputs.nuget-url }} \
          --api-key ${{ secrets.nuget-api-key }} \
          --skip-duplicate \
          /p:PackageVersion=${{ steps.version.outputs.version-without-v }}
