name: Publish

on:
  workflow_call:
    inputs:
      project-path:
        type: string
      nuget-url:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
    secrets:
      nuget-api-key:
        required: true

env:
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}/output

jobs:

  build:
    uses: maik-hasler/workflows/.github/workflows/build.yml@main
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
      project-path: ${{ inputs.project-path }}
      
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack project
        run: |
          dotnet pack ${{ inputs.project-path }} \
          --no-restore \
          --no-build \
          --configuration Release \
          --include-symbols \
          --output ${{ env.PACKAGE_OUTPUT_PATH }}
          -p:PackageVersion=${{ steps.version.outputs.version-without-v }} \

      - name: Publish to NuGet gallery
        run: |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.nupkg \
          -s ${{ inputs.nuget-url }}
          -k ${{ secrets.nuget-api-key }} \
          /p:PackageVersion=${{ steps.version.outputs.version-without-v }}
